version: '3.6'

services:
  authentication-apis:
    container_name: apicontainer
    # image: node:14.4
    build: ./
    command: npm run dev
    working_dir: /authentication-apis
    ports: 
      - "3001:3001"
    volumes:
      - ./:/authentication-apis
